# Must match Machovy API_KEY for testing to work
BITPAY_API_KEY = ENV['BITPAY_API_KEY'].nil? ? 'blah' : ENV['BITPAY_API_KEY']

EXPIRED_STATUS_RESPONSE_AMT = 1111.11
INVALID_STATUS_RESPONSE_AMT = 9999.99
  
MINIMUM_BTC_PRICE = 0.1
